name: rzd

services:
  bot:
    image: airndlab/rzd-bot:2024.10.13-08-00
    volumes:
      - ./config:/config
    environment:
      - BOT_TOKEN=${BOT_TOKEN}
      - BOT_MESSAGES_FILE_PATH=/config/bot-messages.yml
      - QNA_URL=http://158.160.85.147:8082
    ports:
      - 8092:8088
    networks:
      - rzd-net

#  metabase:
#    image: metabase/metabase:v0.50.29
#    ports:
#      - 3000:3000
#    volumes:
#      - ./dbs:/data/dbs
#    environment:
#      - MB_DB_FILE=/data/dbs/metabase.db
#      - MB_DB_TYPE=h2

networks:
  rzd-net:
