name: rzd

services:
  vllm:
    image: vllm/vllm-openai:v0.6.2
    ipc: host
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              device_ids: [ '0' ]
              capabilities: [ gpu ]
    environment:
      - HUGGING_FACE_HUB_TOKEN=${HUGGING_FACE_HUB_TOKEN}
    volumes:
      - ~/.cache/huggingface:/root/.cache/huggingface
    command: --model Qwen/Qwen2.5-14B-Instruct-GPTQ-Int4 --quantization gptq --device cuda
    networks:
      - rzd-net

  qna:
    image: airndlab/rzd-qna:2024.10.12-19-48
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              device_ids: [ '0' ]
              capabilities: [ gpu ]
    ports:
      - 8080:8080
    volumes:
      - ./config:/config
      - ./dataset:/data/dataset
      - ./dbs:/data/dbs
    environment:
      - HF_HUB_DOWNLOAD_TIMEOUT=600
      - QNA_DB_PATH=/data/dbs/qna.db
      - DATASET_DIR_PATH=/data/dataset
      - MODEL_NAME=Qwen/Qwen2.5-14B-Instruct-GPTQ-Int4
      - MODEL_URL=http://vllm:8000/v1
      - MODEL_CONFIG_FILE_PATH=/config/model-config.json
      - PROFILES_FILE_PATH=/config/profiles.json
      - PROFILES_DEFAULT_ID=young
    networks:
      - rzd-net

  bot:
    image: airndlab/rzd-bot:2024.10.12-10-56
    volumes:
      - ./config:/config
    environment:
      - BOT_TOKEN=${BOT_TOKEN}
      - BOT_MESSAGES_FILE_PATH=/config/bot-messages.yml
      - QNA_URL=http://qna:8080
    networks:
      - rzd-net

  metabase:
    image: metabase/metabase:v0.50.29
    ports:
      - 3000:3000
    volumes:
      - ./dbs:/data/dbs
    environment:
      - MB_DB_FILE=/data/dbs/metabase.db
      - MB_DB_TYPE=h2

networks:
  rzd-net: