name: rzd

services:
  vllm:
    image: vllm/vllm-openai:v0.6.2
    ipc: host
    gpus: all
    deploy:
      resources:
        reservations:
          devices:
            - capabilities: [gpu]
    environment:
      - HUGGING_FACE_HUB_TOKEN=${HUGGING_FACE_HUB_TOKEN}
    volumes:
      - ~/.cache/huggingface:/root/.cache/huggingface
    ports:
      - "8000:8000"
    command:
      - --model ${MODEL_NAME}
      - --quantization ${QUANTIZATION}
