start: |
  Здравствуйте! Я — *🚇Рельсик*, ваш умный персональный помощник! 🤖 Я изучил все нормативные документы и теперь могу помогать вам находить самую важную и полезную информацию о льготах и гарантиях, которые предлагает наша компания.
  
  Для вашего удобства я сгруппировал льготы по нескольким тематическим категориям:  
  1.	🚆 Бесплатный проезд
  2.	🌴 Отпуск
  3.	🏥 Здоровье
  4.	🎉 Досуг
  5.	👨‍👩‍👧‍👦 Семейное благополучие
  6.	💼 Компенсируемый социальный пакет и бонусы
  7.	🎓 Молодежь
  8.	🛋 Комфортные условия
  9.	👵 Перед выходом на пенсию
  10.	🤝 Корпоративное волонтерство
  11.	🏃‍♂️ Здоровый образ жизни
  
  А чтобы Вы быстрее освоились, я подготовил несколько профилей, которые хорошо демонстрируют специфику льгот. 
  Выберите подходящий профиль, и я помогу ответить на вопросы и подбирать для Вас полезную информацию!
  
  Если захотите поменять профиль позже — не проблема, просто дайте мне знать! 😊
answer: |
  {answer}
answer-no: "Извините, я не нашёл подходящий ответ на ваш вопрос. 😩"
like: Спасибо за оценку - рады что Вам понравилось!
dislike: Спасибо за оценку - вы помогаете нам стать лучше!
error: |
  🚂 Ой, что-то пошло не так!
  Пожалуйста, попробуйте еще раз позже.
  Если проблема сохраняется, сообщите администратору.
