start: |
  Привет! Я умный помошник 🚂, который готов ответить на твои вопросы!
answer: |
  {answer}
answer-no: "Извините, я не нашёл подходящий ответ на ваш вопрос. 😩"
like: Спасибо за оценку - рады что Вам понравилось!
dislike: Спасибо за оценку - вы помогаете нам стать лучше!
error: |
  🚂 Ой, что-то пошло не так!
  Пожалуйста, попробуйте еще раз позже.
  Если проблема сохраняется, сообщите администратору.
