start: |
  Здравствуйте! Я — *🚇Рельсик*, Ваш умный персональный помощник! 
  
  Я изучил все нормативные документы и теперь буду помогать Вам находить самую важную и полезную информацию.
  
  А чтобы Вы быстрее освоились, я подготовил несколько профилей, один из которых уже выбран. 
  Если захотите поменять профиль позже — можете сделать это через меню! 😊
  
  В разделе часто задаваемые вопросы /faq и Путеводителем нового сотрудника /guide Вы также найдёте много полезной информации для успешного старта.
answer: |
  {answer}
answer-no: "Извините, я не нашёл подходящий ответ на ваш вопрос. 😩"
like: Спасибо за оценку - рады что Вам понравилось!
dislike: Спасибо за оценку - вы помогаете нам стать лучше!
error: |
  🚂 Ой, что-то пошло не так!
  Пожалуйста, попробуйте еще раз позже.
  Если проблема сохраняется, сообщите администратору.
