start: |
  *Привет! Я ваш личный помощник по социальным льготам в ОАО «РЖД»!*

  Моя задача — помочь вам разобраться в льготах и компенсациях, на которые вы имеете право. Для этого мне нужно немного узнать о вас. Чем больше информации, тем точнее я смогу подобрать льготы, соответствующие вашему региону, стажу и семейному положению.

  Для удобства тестирования вы можете выбрать одну из готовых персон. Нажмите на кнопку, чтобы продолжить!
answer: |
  {answer}
answer-no: "Извините, я не нашёл подходящий ответ на ваш вопрос. 😩"
like: Спасибо за оценку - рады что Вам понравилось!
dislike: Спасибо за оценку - вы помогаете нам стать лучше!
error: |
  🚂 Ой, что-то пошло не так!
  Пожалуйста, попробуйте еще раз позже.
  Если проблема сохраняется, сообщите администратору.
