ENG_TO_RUS:
  title: "заголовок"
  description: "описание"
  person_name: "имя"
  position: "должность"
  organization: "организация"
  region: "регион"
  sex: "пол"
  age: "возраст"
  child_count: "количество детей"
  work_years: "стаж работы"
  veteran_of_labor: "ветеран труда"

RUS_GENITIVE:
  "заголовок": "заголовка"
  "описание": "описания"
  "имя": "имени"
  "должность": "должности"
  "организация": "организации"
  "регион": "региона"
  "пол": "пола"
  "возраст": "возраста"
  "количество детей": "количества детей"
  "стаж работы": "стажа работы"
  "ветеран труда": "ветерана труда"

RUS_INSTRUMENTAL:
  "заголовок": "заголовком"
  "описание": "описанием"
  "имя": "именем"
  "должность": "должностью"
  "организация": "организацией"
  "регион": "регионом"
  "пол": "полом"
  "возраст": "возрастом"
  "количество детей": "количеством детей"
  "стаж работы": "стажем работы"
  "ветеран труда": "ветераном труда"
