faq:
  - section: "1. Бесплатный проезд"
    questions:
      - question: "Какие категории сотрудников имеют право на бесплатный проезд?"
        answer: "Бесплатный проезд предоставляется всем сотрудникам, включая право на проезд в пригородных поездах и дальнем следовании по условиям, указанным в коллективном договоре."
  - section: "2. Отпуск"
    questions:
      - question: "*Вопрос*: Сколько дней отпуска предоставляется сотрудникам?"
        answer: "*Ответ*: Основной оплачиваемый отпуск составляет 28 календарных дней. Сотрудники до 18 лет и инвалиды имеют дополнительные дни отпуска."

  - section: "3. Здоровье"
    questions:
      - question: "*Вопрос*: Какие медицинские услуги покрываются для сотрудников?"
        answer: "*Ответ*: Сотрудники могут воспользоваться медицинским страхованием, включая ежегодные медосмотры, а также программы санаторно-курортного лечения для поддержания здоровья."

  - section: "4. Досуг"
    questions:
      - question: "*Вопрос*: Какие льготы предоставляются для отдыха и досуга?"
        answer: "*Ответ*: Компания предоставляет путевки в санатории и детские оздоровительные лагеря, а также доступ к корпоративным культурным и спортивным мероприятиям."

  - section: "5. Семья"
    questions:
      - question: "*Вопрос*: Какие льготы предусмотрены для сотрудников с детьми?"
        answer: "*Ответ*: Сотрудникам предоставляются дополнительные отпуска по уходу за детьми, а также путевки в оздоровительные лагеря и помощь в образовании детей сотрудников."

  - section: "6. Компенсируемый социальный пакет. Бонусный пакет"
    questions:
      - question: "*Вопрос*: Что входит в компенсируемый социальный пакет?"
        answer: "*Ответ*: Компенсируемый социальный пакет включает возмещение затрат на социальные услуги (например, медицинские или образовательные), в пределах установленного лимита, для сотрудников, достигших значительных производственных успехов или занимающих редкие профессии."
      - question: "*Вопрос*: Как работает бонусный пакет?"
        answer: "*Ответ*: Бонусный пакет предоставляет поощрения сотрудникам за личный вклад в повышение эффективности компании, активное участие в корпоративных проектах и высокие результаты труда."

  - section: "7. Молодежь"
    questions:
      - question: "*Вопрос*: Какие программы поддержки существуют для молодых сотрудников?"
        answer: "*Ответ*: Молодежные программы включают льготы на обучение, программы карьерного роста, участие в корпоративных мероприятиях и поддержку для молодых специалистов, работающих в отдалённых регионах."
      - question: "*Вопрос*: Как получить льготы на обучение в компании?"
        answer: "*Ответ*: Сотрудники могут получить льготы на обучение в рамках корпоративных образовательных программ, а также компенсации за обучение в профильных учебных заведениях."

  - section: "8. Комфортные условия"
    questions:
      - question: "*Вопрос*: Какие меры компания предпринимает для создания комфортных условий труда?"
        answer: "*Ответ*: Компания обеспечивает сотрудников всеми необходимыми средствами индивидуальной защиты, оборудованными рабочими местами и поддерживает безопасные условия труда на производственных объектах."
      - question: "*Вопрос*: Какие льготы предусмотрены для сотрудников, работающих в отдалённых и сложных условиях?"
        answer: "*Ответ*: Для сотрудников, работающих в труднодоступных регионах или в сложных климатических условиях, предоставляются дополнительные компенсации, надбавки и улучшенные условия проживания."

  - section: "9. Перед выходом на пенсию"
    questions:
      - question: "*Вопрос*: Как компания поддерживает сотрудников перед выходом на пенсию?"
        answer: "*Ответ*: Сотрудникам, приближающимся к пенсионному возрасту, предоставляются дополнительные консультации, помощь в подготовке документов для выхода на пенсию и возможность получения дополнительного отпуска."
      - question: "*Вопрос*: Какие льготы предусмотрены для неработающих пенсионеров компании?"
        answer: "*Ответ*: Неработающим пенсионерам ОАО «РЖД» предоставляются медицинские льготы, социальная поддержка, а также доступ к корпоративным санаториям и путевкам."

  - section: "10. Корпоративное волонтерство"
    questions:
      - question: "*Вопрос*: Что включает программа корпоративного волонтерства?"
        answer: "*Ответ*: Программа корпоративного волонтерства поддерживает участие сотрудников в социальных и благотворительных проектах, предоставляет отпуска для участия в волонтерской деятельности и содействует в организации корпоративных волонтерских акций."
      - question: "*Вопрос*: Как можно стать корпоративным волонтером?"
        answer: "*Ответ*: Для участия в волонтерских проектах необходимо подать заявку в HR-службу или зарегистрироваться через внутренние корпоративные платформы, где представлены все доступные волонтерские инициативы."

  - section: "11. Здоровый образ жизни"
    questions:
      - question: "*Вопрос*: Какие программы поддержки ЗОЖ доступны сотрудникам?"
        answer: "*Ответ*: Программы включают участие в спортивных клубах, скидки на абонементы в фитнес-залы, организацию корпоративных спортивных мероприятий и ежегодные медицинские осмотры."
      - question: "*Вопрос*: Какие спортивные мероприятия проводятся в компании?"
        answer: "*Ответ*: В компании регулярно организуются массовые спортивные мероприятия, включая соревнования, корпоративные забеги, а также программы поддержки физической активности через корпоративные спортклубы."